### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by Ericonaldo** [siddhanthaldar/ROT#2]
https://github.com/siddhanthaldar/ROT/blob/main/ROT/agent/dac.py#L187

```
dist = self.actor(obs, stddev)
next_action = dist.sample(clip=self.stddev_clip)
target_Q1, target_Q2 = self.critic_target(next_obs, next_action)
```

This is computing the action for the next observation, but you write `obs` instead of `next_obs` here.

**Comment by siddhanthaldar** [comment]
Hi! Thank you for pointing this out. I had pushed the wrong script for DAC and have corrected the code now. Feel free to run the corrected code to get results for DAC consistent with the paper.
