### ISSUE TITLE
Make Dataset link public?

### ISSUE THREAD

**Issue by ethanluoyc** [siddhanthaldar/ROT#3]
Hi,

I was wondering if it would be possible to make the dataset link public (currently, it is a private, view-only). I think it would be handy as only public links can be used for automatically downloading the dataset (see [link](https://github.com/CenterForOpenScience/osf.io/issues/8256)).

**Comment by siddhanthaldar** [comment]
Hi,

Thanks for bringing that to my notice. I have made the link public. You should be able to download the dataset and the weights now.
