### ISSUE TITLE
About how to collect dataset

### ISSUE THREAD

**Issue by sunhan1997** [siddhanthaldar/ROT#4]
Hello, thank you for your work. We want to collect a dataset about robot arm. I find there is a ` joy.py` that controls the robot.  Do you use `Xbox ` and  `pygame ` to control the robot? And I see that you can control the translation of the robot end, then how to control the rotation of the robot end?

**Comment by siddhanthaldar** [comment]
Hi,

Thank you for your interest in our work. Here are the answers to your questions -

- We used a Logitech joystick controller for collecting the data on the robot. The controller was interfaced with our code using `pygame`.
- In this work, we did not control the rotation of the robot end. However, it can be done by changing the `robot.py` file [here](https://github.com/siddhanthaldar/ROT/blob/41ef7b98ca3950b9f31dd174f306cbe6916a09c9/teleop/robot.py#L112) to pass your own values of roll, pitch, and yaw to the robot controller.

Hope that helps!
